#!/bin/bash
# barber 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {
    dx download "$vcf_file" -o input_file
    dx download "$vcf_file_index" -o input_file.csi
    dx download "$rename_file" -o "rename.tsv"
    tmp_dir="tmp"
    
    # Create a temporary directory
    mkdir -p "$tmp_dir"
    # Step 1: Remove tags from the original VCF file
    bcftools view -r $chr input_file -o split_input.vcf.gz -Oz --threads 4
    bcftools annotate --threads 4 -Oz -o "$tmp_dir/test_notags.vcf.gz" -x ^INFO/REF,^INFO/REPID,^FORMAT/GT split_input.vcf.gz
    bcftools index "$tmp_dir/test_notags.vcf.gz"
    
    
    # Step 2: Process the VCF file, rename REPID values, and convert genotypes
    bcftools query -f '%INFO/REPID\t%INFO/REF\t%ALT[\t%GT]\n' "$tmp_dir/test_notags.vcf.gz" > "$tmp_dir/temp_output.txt"
    bash rename_repids.sh $tmp_dir/temp_output.txt rename.tsv $tmp_dir/rename_output.txt
    awk '$1 ~ /^chr/' "$tmp_dir/rename_output.txt" > "$tmp_dir/output.txt"
    awk -f convert_genotypes.awk "$tmp_dir/output.txt" > "$tmp_dir/converted_output.txt"
    
    # Step 3: Split variants and recode them
    awk -f split_variants.awk "$tmp_dir/output.txt" > "$tmp_dir/biallelic_variants.txt"
    awk -f recoding_script.awk "$tmp_dir/converted_output.txt" "$tmp_dir/biallelic_variants.txt" > "$tmp_dir/recoded_variants.txt"
    bcftools query -l input_file > samples.txt
    Rscript create_vcf.R "$tmp_dir/recoded_variants.txt" "samples.txt" "$tmp_dir/chromosome_$chr.vcf"
    bgzip -f "$tmp_dir/chromosome_$chr.vcf"
    bcftools index "$tmp_dir/chromosome_$chr.vcf.gz"
    
    
    
    
    echo "Processing complete."

    
    
   
    
    final_file="$tmp_dir/chromosome_$chr.vcf.gz"
    filename_after_upload="${chr}_split.vcf.gz"
    output="${output_folder}/${filename_after_upload}"
    results_file=$(dx upload $final_file --brief --path "$output" -p)
    dx-jobutil-add-output split_chr "$results_file" --class=file
    
}
